dist: trusty
sudo: false
language: python
python: 2.7
install:
  - pip install Lektor
  - pushd lektor-app && npm install --global npm@latest && popd
script:
  - lektor build -f lektor-app/webpack
after_success:
#   - test "$TRAVIS_PULL_REQUEST" == "false" && test "$TRAVIS_BRANCH" == "master" && lektor deploy production
    - test "$TRAVIS_PULL_REQUEST" == "false" && test "$TRAVIS_BRANCH" == "master"
cache: pip
# disabled because of travis issues
#cache:
#  directories:
#    - $HOME/.cache/pip
#    - $HOME/.cache/lektor/builds
