---
apiVersion: v1
kind: Service
metadata:
  name: hello-lektor
spec:
  selector:
    app: hello-lektor

  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata: {name: hello-lektor}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-lektor
      track: stable
  strategy:
    rollingUpdate: {maxSurge: 1, maxUnavailable: 0}
    type: RollingUpdate
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: hello-lektor
        track: stable
      name: hello-lektor
    spec:
      containers:
      - image: mahajany/hello-lektor:v1
        imagePullPolicy: IfNotPresent
        name: hello-lektor
        resources:
          limits:
            memory: 0.25G
            cpu: 0.25
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
